-- Migration: Simplify quiz_questions choices format
-- Run this in Supabase SQL Editor after uploading schema files
-- This documents the schema change to support simplified choices format from n8n

-- ============================================================================
-- SCHEMA CHANGE DOCUMENTATION
-- ============================================================================
-- The quiz_questions.choices column now supports TWO formats:
--
-- 1. NEW FORMAT (from n8n workflows):
--    ["answer text A", "answer text B", "answer text C", "answer text D"]
--
-- 2. LEGACY FORMAT (backwards compatible):
--    [{"label": "A", "text": "answer A"}, {"label": "B", "text": "answer B"}, ...]
--
-- The correct_label column (added in uploads_schema.sql) stores 'A', 'B', 'C', or 'D'
-- The answer_hash column stores lowercase 'a', 'b', 'c', 'd' for MCQ questions
-- ============================================================================

-- No actual migration needed - JSONB column accepts both formats
-- Frontend quiz-player.tsx has been updated with getNormalizedChoices() helper
-- to handle both formats seamlessly

-- ============================================================================
-- EXAMPLE USAGE
-- ============================================================================

-- Insert with NEW simplified format (matches n8n output):
-- INSERT INTO quiz_questions (quiz_id, type, prompt, choices, answer_hash, correct_label, hint)
-- VALUES (
--   '<quiz_id>',
--   'mcq',
--   'What is 2 + 2?',
--   '["3", "4", "5", "6"]',
--   'b',
--   'B',
--   'Add the two numbers together'
-- );

-- Insert with LEGACY format (still works):
-- INSERT INTO quiz_questions (quiz_id, type, prompt, choices, answer_hash, correct_label, hint)
-- VALUES (
--   '<quiz_id>',
--   'mcq',
--   'What is 2 + 2?',
--   '[{"label": "A", "text": "3"}, {"label": "B", "text": "4"}, {"label": "C", "text": "5"}, {"label": "D", "text": "6"}]',
--   'b',
--   'B',
--   'Add the two numbers together'
-- );

-- ============================================================================
-- n8n INTEGRATION
-- ============================================================================
-- Your n8n "POST Questions to Supabase" node should use this mapping:
--
-- {{
--   (
--     $('Parse and Validate LLM JSON').item.json.questions || []
--   ).map(q => {
--     const idx = (q.choices || []).indexOf(q.correct_choice);
--     const label = idx >= 0 ? ['A','B','C','D'][idx] : null;
--
--     return {
--       quiz_id: ($('POST Quiz to Supabase').item.json.id || $('POST Quiz to Supabase').item.json[0]?.id),
--       type: 'mcq',
--       prompt: (q.prompt || '').trim(),
--       choices: q.choices,                 // Simple array - Supabase handles JSONB conversion
--       answer_hash: label?.toLowerCase(),  // 'a', 'b', 'c', or 'd'
--       hint: q.hint ?? null,
--       correct_label: label                // 'A', 'B', 'C', or 'D'
--     };
--   })
-- }}

-- ============================================================================
-- VERIFICATION QUERY
-- ============================================================================
-- Check which format your existing questions use:
-- SELECT 
--   id,
--   prompt,
--   CASE 
--     WHEN jsonb_typeof(choices->0) = 'string' THEN 'NEW (string array)'
--     WHEN jsonb_typeof(choices->0) = 'object' THEN 'LEGACY (object array)'
--     ELSE 'UNKNOWN'
--   END as format,
--   choices
-- FROM quiz_questions
-- WHERE type = 'mcq';
